/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [VideoID]
      ,[TitleEn]
      ,[TitleAr]
      ,[DescriptionEn]
      ,[DescriptionAr]
      ,[ImagePath]
      ,[Link]
      ,[CreatedAt]
      ,[CreatedByUserID]
      ,[UpdatedAt]
      ,[UpdatedByUserID]
      ,[IsDeleted]
  FROM [NGD_Website].[Website].[Videos]
